apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datashelter-cronjob
spec:
  schedule: "{{ .Values.scheduling.schemaTotal.frequency }}" # O schedule do CronJob pode ser mantido via values.yaml, mas pode ser referenciado do ConfigMap se desejar
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: datashelter-cronjob
              image: "{{ .Values.image.repository }}"
              env:
                - name: MYSQL_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: MYSQL_HOST
                - name: MYSQL_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: MYSQL_PORT
                - name: MYSQL_USER
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: MYSQL_USER
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: password
                - name: BACKUP_SCHEMA_TOTAL
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: BACKUP_SCHEMA_TOTAL
                - name: BACKUP_SCHEMA_INCREMENTAL
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: BACKUP_SCHEMA_INCREMENTAL
                - name: BACKUP_SERVER_TOTAL
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: BACKUP_SERVER_TOTAL
                - name: BACKUP_SERVER_INCREMENTAL
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: BACKUP_SERVER_INCREMENTAL
                - name: SCHEDULE_SCHEMA_TOTAL_FREQUENCY
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SCHEMA_TOTAL_FREQUENCY
                - name: SCHEDULE_SCHEMA_TOTAL_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SCHEMA_TOTAL_TIME
                - name: SCHEDULE_SCHEMA_TOTAL_MAX_EXECUTION_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SCHEMA_TOTAL_MAX_EXECUTION_TIME
                - name: SCHEDULE_SCHEMA_INCREMENTAL_FREQUENCY
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SCHEMA_INCREMENTAL_FREQUENCY
                - name: SCHEDULE_SCHEMA_INCREMENTAL_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SCHEMA_INCREMENTAL_TIME
                - name: SCHEDULE_SCHEMA_INCREMENTAL_MAX_EXECUTION_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SCHEMA_INCREMENTAL_MAX_EXECUTION_TIME
                - name: SCHEDULE_SERVER_TOTAL_FREQUENCY
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_TOTAL_FREQUENCY
                - name: SCHEDULE_SERVER_TOTAL_DAYOFWEEK
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_TOTAL_DAYOFWEEK
                - name: SCHEDULE_SERVER_TOTAL_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_TOTAL_TIME
                - name: SCHEDULE_SERVER_TOTAL_MAX_EXECUTION_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_TOTAL_MAX_EXECUTION_TIME
                - name: SCHEDULE_SERVER_INCREMENTAL_FREQUENCY
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_INCREMENTAL_FREQUENCY
                - name: SCHEDULE_SERVER_INCREMENTAL_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_INCREMENTAL_TIME
                - name: SCHEDULE_SERVER_INCREMENTAL_MAX_EXECUTION_TIME
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SCHEDULE_SERVER_INCREMENTAL_MAX_EXECUTION_TIME
                - name: NOTIFICATION_EMAIL_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: NOTIFICATION_EMAIL_ENABLED
                - name: SMTP_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SMTP_HOST
                - name: SMTP_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SMTP_PORT
                - name: SMTP_USER
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: SMTP_USER
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: smtp-secret
                      key: password
                - name: NOTIFICATION_EMAIL_RECIPIENTS
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: NOTIFICATION_EMAIL_RECIPIENTS
                - name: DO_SPACES_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: DO_SPACES_ENABLED
                - name: DO_SPACES_ACCESSKEY
                  valueFrom:
                    secretKeyRef:
                      name: do-spaces-secret
                      key: accessKey
                - name: DO_SPACES_SECRETKEY
                  valueFrom:
                    secretKeyRef:
                      name: do-spaces-secret
                      key: secretKey
                - name: DO_SPACES_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: DO_SPACES_REGION
                - name: DO_SPACES_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: DO_SPACES_BUCKET
                - name: AWS_S3_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: AWS_S3_ENABLED
                - name: AWS_S3_ACCESSKEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-s3-secret
                      key: accessKey
                - name: AWS_S3_SECRETKEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-s3-secret
                      key: secretKey
                - name: AWS_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: AWS_S3_REGION
                - name: AWS_S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: AWS_S3_BUCKET
                - name: RSA_PUBLICKEY
                  valueFrom:
                    secretKeyRef:
                      name: rsa-publickey-secret
                      key: publicKey
                - name: RETENTION_DAYS
                  valueFrom:
                    configMapKeyRef:
                      name: datashelter-config
                      key: RETENTION_DAYS
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
              command: ["/bin/sh", "-c", "/scripts/backup.sh"]
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
