AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a secure S3 bucket for file repository with restricted access
  and an IAM user with limited permissions to upload files.
  
  # Key Features:
  # - Creates a secure S3 bucket with enforced encryption (AES256)
  # - Requires HTTPS connections for all S3 operations
  # - Creates an IAM user with restricted permissions:
  #   * Can upload files to the bucket
  #   * Can set object expiration metadata via tagging
  #   * Can list bucket contents
  #   * CANNOT delete files (explicitly denied)
  # - Applies proper resource tagging for governance
  # - Creates access credentials for programmatic access
  # - Implements security best practices for data protection

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    AllowedPattern: '^[a-z0-9][a-z0-9\.\-]{1,61}[a-z0-9]$'
    ConstraintDescription: Bucket name must be between 3 and 63 characters, contain only lowercase letters, numbers, periods, and dashes, and start and end with a letter or number.
  
  IamUser:
    Type: String
    Description: Name for the IAM user
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: IAM user name must be between 1 and 64 alphanumeric characters or these special characters - _+=,.@-
  
  Owner:
    Type: String
    Description: Owner name for resource tagging
  
  Application:
    Type: String
    Description: Application name for resource tagging

Resources:
  SecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Description
          Value: Secure bucket for file repository with restricted access
        - Key: Owner
          Value: !Ref Owner
        - Key: Application
          Value: !Ref Application
        - Key: Author
          Value: https://github.com/devopsvanilla/datashelter

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnencryptedUploads
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${SecureS3Bucket}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'
          - Sid: EnforceSecureTransport
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !Sub 'arn:aws:s3:::${SecureS3Bucket}'
              - !Sub 'arn:aws:s3:::${SecureS3Bucket}/*'
            Condition:
              Bool:
                aws:SecureTransport: false

  DataShelterUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref IamUser
      Tags:
        - Key: Description
          Value: IAM user with limited permissions for secure file uploads
        - Key: Owner
          Value: !Ref Owner
        - Key: Application
          Value: !Ref Application
        - Key: Author
          Value: https://github.com/devopsvanilla/datashelter

  DataShelterUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'S3UploadOnlyPolicy-${IamUser}'
      Description: Policy granting an IAM user permission to upload and tag objects in an S3 bucket while preventing deletions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowUploadFiles
            Effect: Allow
            Action: s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${SecureS3Bucket}/*'
          - Sid: AllowSetExpirationMetadata
            Effect: Allow
            Action: s3:PutObjectTagging
            Resource: !Sub 'arn:aws:s3:::${SecureS3Bucket}/*'
          - Sid: AllowListBucketContents
            Effect: Allow
            Action: s3:ListBucket
            Resource: !Sub 'arn:aws:s3:::${SecureS3Bucket}'
          - Sid: DenyFileDeletion
            Effect: Deny
            Action: s3:DeleteObject
            Resource: !Sub 'arn:aws:s3:::${SecureS3Bucket}/*'
      Users:
        - !Ref DataShelterUser

  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref DataShelterUser

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref SecureS3Bucket

  UserName:
    Description: Name of the IAM User
    Value: !Ref DataShelterUser

  AccessKey:
    Description: Access Key ID for the IAM User
    Value: !Ref UserAccessKey

  SecretKey:
    Description: Secret Access Key for the IAM User
    Value: !GetAtt UserAccessKey.SecretAccessKey